Los tasadores inmobiliarios en Estados Unidos evalúan propiedades para que bancos, compradores y vendedores tomen decisiones financieras bien fundadas. Una tasación incorrecta puede llevar a que un banco otorgue un préstamo por encima del valor real del inmueble, o que un vendedor pierda dinero por subvaluar su propiedad.

El dataset de Ames, Iowa, contiene información detallada sobre más de 80 características de cada casa vendida entre 2006 y 2010: metros cuadrados, calidad de los materiales de construcción, año de construcción, tipo de barrio, cantidad de baños, si tiene garaje, estado del sótano, y muchas más. El objetivo es predecir el precio de venta final de cada propiedad.

Como debemos estimar un precio, estamos ante un problema de regresión.

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold

In [2]:
ds = fetch_openml(name="house_prices", as_frame=True)
ds.keys() # ['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url']
ds['categories'] #None
ds['feature_names']
ds['target_names'] #'SalePrice'
ds['details'] #información general sobre la base de datos
ds['url']
ds['target']
ds['data'] #dataframe de 1460 filas y 80 atributos
print(ds['DESCR']) #de esta forma se imprime por renglones

Ask a home buyer to describe their dream house, and they probably won't begin with the height of the basement ceiling or the proximity to an east-west railroad. But this playground competition's dataset proves that much more influences price negotiations than the number of bedrooms or a white-picket fence.

With 79 explanatory variables describing (almost) every aspect of residential homes in Ames, Iowa, this competition challenges you to predict the final price of each home.

MSSubClass: Identifies the type of dwelling involved in the sale.

        20	1-STORY 1946 & NEWER ALL STYLES
        30	1-STORY 1945 & OLDER
        40	1-STORY W/FINISHED ATTIC ALL AGES
        45	1-1/2 STORY - UNFINISHED ALL AGES
        50	1-1/2 STORY FINISHED ALL AGES
        60	2-STORY 1946 & NEWER
        70	2-STORY 1945 & OLDER
        75	2-1/2 STORY ALL AGES
        80	SPLIT OR MULTI-LEVEL
        85	SPLIT FOYER
        90	DUPLEX - ALL STYLES AND AGES
       120	1-STORY PUD (Planned Unit Development) - 1946 & NEWER
       150	1-1/2 STORY PUD - ALL AGES
       160	2-STORY PUD - 1946 & NEWER
       180	PUD - MULTILEVEL - INCL SPLIT LEV/FOYER
       190	2 FAMILY CONVERSION - ALL STYLES AND AGES

MSZoning: Identifies the general zoning classification of the sale.

       A	Agriculture
       C	Commercial
       FV	Floating Village Residential
       I	Industrial
       RH	Residential High Density
       RL	Residential Low Density
       RP	Residential Low Density Park
       RM	Residential Medium Density

LotFrontage: Linear feet of street connected to property

LotArea: Lot size in square feet

Street: Type of road access to property

       Grvl	Gravel
       Pave	Paved

Alley: Type of alley access to property

       Grvl	Gravel
       Pave	Paved
       NA 	No alley access

LotShape: General shape of property

       Reg	Regular
       IR1	Slightly irregular
       IR2	Moderately Irregular
       IR3	Irregular

LandContour: Flatness of the property

       Lvl	Near Flat/Level
       Bnk	Banked - Quick and significant rise from street grade to building
       HLS	Hillside - Significant slope from side to side
       Low	Depression

Utilities: Type of utilities available

       AllPub	All public Utilities (E,G,W,& S)
       NoSewr	Electricity, Gas, and Water (Septic Tank)
       NoSeWa	Electricity and Gas Only
       ELO	Electricity only

LotConfig: Lot configuration

       Inside	Inside lot
       Corner	Corner lot
       CulDSac	Cul-de-sac
       FR2	Frontage on 2 sides of property
       FR3	Frontage on 3 sides of property

LandSlope: Slope of property

       Gtl	Gentle slope
       Mod	Moderate Slope
       Sev	Severe Slope

Neighborhood: Physical locations within Ames city limits

       Blmngtn	Bloomington Heights
       Blueste	Bluestem
       BrDale	Briardale
       BrkSide	Brookside
       ClearCr	Clear Creek
       CollgCr	College Creek
       Crawfor	Crawford
       Edwards	Edwards
       Gilbert	Gilbert
       IDOTRR	Iowa DOT and Rail Road
       MeadowV	Meadow Village
       Mitchel	Mitchell
       Names	North Ames
       NoRidge	Northridge
       NPkVill	Northpark Villa
       NridgHt	Northridge Heights
       NWAmes	Northwest Ames
       OldTown	Old Town
       SWISU	South & West of Iowa State University
       Sawyer	Sawyer
       SawyerW	Sawyer West
       Somerst	Somerset
       StoneBr	Stone Brook
       Timber	Timberland
       Veenker	Veenker

Condition1: Proximity to various conditions

       Artery	Adjacent to arterial street
       Feedr	Adjacent to feeder street
       Norm	Normal
       RRNn	Within 200' of North-South Railroad
       RRAn	Adjacent to North-South Railroad
       PosN	Near positive off-site feature--park, greenbelt, etc.
       PosA	Adjacent to postive off-site feature
       RRNe	Within 200' of East-West Railroad
       RRAe	Adjacent to East-West Railroad

Condition2: Proximity to various conditions (if more than one is present)

       Artery	Adjacent to arterial street
       Feedr	Adjacent to feeder street
       Norm	Normal
       RRNn	Within 200' of North-South Railroad
       RRAn	Adjacent to North-South Railroad
       PosN	Near positive off-site feature--park, greenbelt, etc.
       PosA	Adjacent to postive off-site feature
       RRNe	Within 200' of East-West Railroad
       RRAe	Adjacent to East-West Railroad

BldgType: Type of dwelling

       1Fam	Single-family Detached
       2FmCon	Two-family Conversion; originally built as one-family dwelling
       Duplx	Duplex
       TwnhsE	Townhouse End Unit
       TwnhsI	Townhouse Inside Unit

HouseStyle: Style of dwelling

       1Story	One story
       1.5Fin	One and one-half story: 2nd level finished
       1.5Unf	One and one-half story: 2nd level unfinished
       2Story	Two story
       2.5Fin	Two and one-half story: 2nd level finished
       2.5Unf	Two and one-half story: 2nd level unfinished
       SFoyer	Split Foyer
       SLvl	Split Level

OverallQual: Rates the overall material and finish of the house

       10	Very Excellent
       9	Excellent
       8	Very Good
       7	Good
       6	Above Average
       5	Average
       4	Below Average
       3	Fair
       2	Poor
       1	Very Poor

OverallCond: Rates the overall condition of the house

       10	Very Excellent
       9	Excellent
       8	Very Good
       7	Good
       6	Above Average
       5	Average
       4	Below Average
       3	Fair
       2	Poor
       1	Very Poor

YearBuilt: Original construction date

YearRemodAdd: Remodel date (same as construction date if no remodeling or additions)

RoofStyle: Type of roof

       Flat	Flat
       Gable	Gable
       Gambrel	Gabrel (Barn)
       Hip	Hip
       Mansard	Mansard
       Shed	Shed

RoofMatl: Roof material

       ClyTile	Clay or Tile
       CompShg	Standard (Composite) Shingle
       Membran	Membrane
       Metal	Metal
       Roll	Roll
       Tar&Grv	Gravel & Tar
       WdShake	Wood Shakes
       WdShngl	Wood Shingles

Exterior1st: Exterior covering on house

       AsbShng	Asbestos Shingles
       AsphShn	Asphalt Shingles
       BrkComm	Brick Common
       BrkFace	Brick Face
       CBlock	Cinder Block
       CemntBd	Cement Board
       HdBoard	Hard Board
       ImStucc	Imitation Stucco
       MetalSd	Metal Siding
       Other	Other
       Plywood	Plywood
       PreCast	PreCast
       Stone	Stone
       Stucco	Stucco
       VinylSd	Vinyl Siding
       Wd Sdng	Wood Siding
       WdShing	Wood Shingles

Exterior2nd: Exterior covering on house (if more than one material)

       AsbShng	Asbestos Shingles
       AsphShn	Asphalt Shingles
       BrkComm	Brick Common
       BrkFace	Brick Face
       CBlock	Cinder Block
       CemntBd	Cement Board
       HdBoard	Hard Board
       ImStucc	Imitation Stucco
       MetalSd	Metal Siding
       Other	Other
       Plywood	Plywood
       PreCast	PreCast
       Stone	Stone
       Stucco	Stucco
       VinylSd	Vinyl Siding
       Wd Sdng	Wood Siding
       WdShing	Wood Shingles

MasVnrType: Masonry veneer type

       BrkCmn	Brick Common
       BrkFace	Brick Face
       CBlock	Cinder Block
       None	None
       Stone	Stone

MasVnrArea: Masonry veneer area in square feet

ExterQual: Evaluates the quality of the material on the exterior

       Ex	Excellent
       Gd	Good
       TA	Average/Typical
       Fa	Fair
       Po	Poor

ExterCond: Evaluates the present condition of the material on the exterior

       Ex	Excellent
       Gd	Good
       TA	Average/Typical
       Fa	Fair
       Po	Poor

Foundation: Type of foundation

       BrkTil	Brick & Tile
       CBlock	Cinder Block
       PConc	Poured Contrete
       Slab	Slab
       Stone	Stone
       Wood	Wood

BsmtQual: Evaluates the height of the basement

       Ex	Excellent (100+ inches)
       Gd	Good (90-99 inches)
       TA	Typical (80-89 inches)
       Fa	Fair (70-79 inches)
       Po	Poor (<70 inches
       NA	No Basement

BsmtCond: Evaluates the general condition of the basement

       Ex	Excellent
       Gd	Good
       TA	Typical - slight dampness allowed
       Fa	Fair - dampness or some cracking or settling
       Po	Poor - Severe cracking, settling, or wetness
       NA	No Basement

BsmtExposure: Refers to walkout or garden level walls

       Gd	Good Exposure
       Av	Average Exposure (split levels or foyers typically score average or above)
       Mn	Mimimum Exposure
       No	No Exposure
       NA	No Basement

BsmtFinType1: Rating of basement finished area

       GLQ	Good Living Quarters
       ALQ	Average Living Quarters
       BLQ	Below Average Living Quarters
       Rec	Average Rec Room
       LwQ	Low Quality
       Unf	Unfinshed
       NA	No Basement

BsmtFinSF1: Type 1 finished square feet

BsmtFinType2: Rating of basement finished area (if multiple types)

       GLQ	Good Living Quarters
       ALQ	Average Living Quarters
       BLQ	Below Average Living Quarters
       Rec	Average Rec Room
       LwQ	Low Quality
       Unf	Unfinshed
       NA	No Basement

BsmtFinSF2: Type 2 finished square feet

BsmtUnfSF: Unfinished square feet of basement area

TotalBsmtSF: Total square feet of basement area

Heating: Type of heating

       Floor	Floor Furnace
       GasA	Gas forced warm air furnace
       GasW	Gas hot water or steam heat
       Grav	Gravity furnace
       OthW	Hot water or steam heat other than gas
       Wall	Wall furnace

HeatingQC: Heating quality and condition

       Ex	Excellent
       Gd	Good
       TA	Average/Typical
       Fa	Fair
       Po	Poor

CentralAir: Central air conditioning

       N	No
       Y	Yes

Electrical: Electrical system

       SBrkr	Standard Circuit Breakers & Romex
       FuseA	Fuse Box over 60 AMP and all Romex wiring (Average)
       FuseF	60 AMP Fuse Box and mostly Romex wiring (Fair)
       FuseP	60 AMP Fuse Box and mostly knob & tube wiring (poor)
       Mix	Mixed

1stFlrSF: First Floor square feet

2ndFlrSF: Second floor square feet

LowQualFinSF: Low quality finished square feet (all floors)

GrLivArea: Above grade (ground) living area square feet

BsmtFullBath: Basement full bathrooms

BsmtHalfBath: Basement half bathrooms

FullBath: Full bathrooms above grade

HalfBath: Half baths above grade

Bedroom: Bedrooms above grade (does NOT include basement bedrooms)

Kitchen: Kitchens above grade

KitchenQual: Kitchen quality

       Ex	Excellent
       Gd	Good
       TA	Typical/Average
       Fa	Fair
       Po	Poor

TotRmsAbvGrd: Total rooms above grade (does not include bathrooms)

Functional: Home functionality (Assume typical unless deductions are warranted)

       Typ	Typical Functionality
       Min1	Minor Deductions 1
       Min2	Minor Deductions 2
       Mod	Moderate Deductions
       Maj1	Major Deductions 1
       Maj2	Major Deductions 2
       Sev	Severely Damaged
       Sal	Salvage only

Fireplaces: Number of fireplaces

FireplaceQu: Fireplace quality

       Ex	Excellent - Exceptional Masonry Fireplace
       Gd	Good - Masonry Fireplace in main level
       TA	Average - Prefabricated Fireplace in main living area or Masonry Fireplace in basement
       Fa	Fair - Prefabricated Fireplace in basement
       Po	Poor - Ben Franklin Stove
       NA	No Fireplace

GarageType: Garage location

       2Types	More than one type of garage
       Attchd	Attached to home
       Basment	Basement Garage
       BuiltIn	Built-In (Garage part of house - typically has room above garage)
       CarPort	Car Port
       Detchd	Detached from home
       NA	No Garage

GarageYrBlt: Year garage was built

GarageFinish: Interior finish of the garage

       Fin	Finished
       RFn	Rough Finished
       Unf	Unfinished
       NA	No Garage

GarageCars: Size of garage in car capacity

GarageArea: Size of garage in square feet

GarageQual: Garage quality

       Ex	Excellent
       Gd	Good
       TA	Typical/Average
       Fa	Fair
       Po	Poor
       NA	No Garage

GarageCond: Garage condition

       Ex	Excellent
       Gd	Good
       TA	Typical/Average
       Fa	Fair
       Po	Poor
       NA	No Garage

PavedDrive: Paved driveway

       Y	Paved
       P	Partial Pavement
       N	Dirt/Gravel

WoodDeckSF: Wood deck area in square feet

OpenPorchSF: Open porch area in square feet

EnclosedPorch: Enclosed porch area in square feet

3SsnPorch: Three season porch area in square feet

ScreenPorch: Screen porch area in square feet

PoolArea: Pool area in square feet

PoolQC: Pool quality

       Ex	Excellent
       Gd	Good
       TA	Average/Typical
       Fa	Fair
       NA	No Pool

Fence: Fence quality

       GdPrv	Good Privacy
       MnPrv	Minimum Privacy
       GdWo	Good Wood
       MnWw	Minimum Wood/Wire
       NA	No Fence

MiscFeature: Miscellaneous feature not covered in other categories

       Elev	Elevator
       Gar2	2nd Garage (if not described in garage section)
       Othr	Other
       Shed	Shed (over 100 SF)
       TenC	Tennis Court
       NA	None

MiscVal: $Value of miscellaneous feature

MoSold: Month Sold (MM)

YrSold: Year Sold (YYYY)

SaleType: Type of sale

       WD 	Warranty Deed - Conventional
       CWD	Warranty Deed - Cash
       VWD	Warranty Deed - VA Loan
       New	Home just constructed and sold
       COD	Court Officer Deed/Estate
       Con	Contract 15% Down payment regular terms
       ConLw	Contract Low Down payment and low interest
       ConLI	Contract Low Interest
       ConLD	Contract Low Down
       Oth	Other

SaleCondition: Condition of sale

       Normal	Normal Sale
       Abnorml	Abnormal Sale -  trade, foreclosure, short sale
       AdjLand	Adjoining Land Purchase
       Alloca	Allocation - two linked properties with separate deeds, typically condo with a garage unit
       Family	Sale between family members
       Partial	Home was not completed when last assessed (associated with New Homes)

Downloaded from openml.org.

In [ ]:
np.min(ds['data']['YearBuilt']) #1872
np.max(ds['data']['YearBuilt']) #2010

2010

Hay un rango muy grande de años de construcción, que probablemente influya en los precios de venta, por lo que debemos tener en cuenta este atributo.

In [3]:
ds['target']

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [8]:
ds['data']

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2008,WD,Normal

Como ya hemos observado, tenemos un problema de regresión. Leyendo la descripción de los atributos y sus posibles valores en ds['DESCR'], vemos que la mayoría de ellos son categóricos. Algunos de ellos tienen órdenes subyacentes (generalmente de calidad de cosas, por ejemplo la condición del garage), pero muchos otros no tienen un orden claro. Esto plantea una dificultad para estimar los precios por medio de alguna función matemática de las variables, como puede ser una regresión lineal.

Comenzamos clasificando los atributos en numéricos (valores que realmente son números), categóricos con orden implícito y categóricos sin orden claro detrás. No tenemos en cuenta el Id, la clave que identifica a cada instancia, por no tener un significado real en el cálculo de un precio.

Numéricas: MoSold, YrSold, LotFrontage, LotArea, OverallQual, OveralCond, YearBuilt, YearRemodAdd, MasVnrArea, BsmtFinSF1, BsmtFinSF2, BsmtUnfSF, TotalBsmtUnfSF, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, Bedroom, Kitchen, TotRmsAbvGrd, Fireplaces, GarageYrBlt, GarageCars, GarageArea, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, MiscVal.

Categóricas con orden implícito: Street, Alley, Lotshape, Utilities, LandSlope, ExterQual, ExterCond, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinType2, HeatingQC, CentralAir, KitchenQual, Functional, FireplaceQu, GarageFinish, GarageQual, GarageCond, PavedDrive, PoolQC, Fence.

Categóricas sin orden implícito: el resto.

In [3]:
def get_data():
    ds = fetch_openml(name="house_prices", as_frame=True)
    X = ds['data']
    y = ds['target']
    return X,y

In [4]:
X,y = get_data()

In [5]:
"""
Preprocesamiento completo del Ames Housing Dataset (pedido a Claude especificando las reglas que se detalla
en esta documentación).
(fetch_openml(name="house_prices")), sin incluir el target (SalePrice) ni el Id.
 
Reglas aplicadas:
- ORDINALES: valor uniforme en [0, 1], peor=0, mejor=1.
  NaN / 'NA' -> 0 (tratado como el peor caso, ya que en Ames significa
  "no tiene esa característica": sin sótano, sin garage, etc.)
- NUMÉRICAS: normalización min-max, mínimo -> 0, máximo -> 1.
  NaN (valores faltantes, ej. LotFrontage, MasVnrArea, GarageYrBlt) -> 0,
  aplicado después de escalar (el min/max se calcula ignorando los NaN).
- NOMINALES: one-hot con pd.get_dummies.
    * Condition1/Condition2, Exterior1st/Exterior2nd y
      BsmtFinType1/BsmtFinType2 comparten el mismo dominio de valores
      posibles, así que se fusionan en un único bloque de dummies:
      no importa si el valor apareció en la primera o la segunda columna.
 
NOTA: BsmtFinType1/BsmtFinType2 se tratan acá como NOMINALES (par fusionado),
a pedido explícito de este mensaje, aunque en la conversación previa se
habían definido como ORDINALES. Si esto no era la intención, hay que
quitarlos de NOMINAL_PAIRED_COLUMNS y devolverlos a ORDINAL_ORDERINGS.
"""
 
import pandas as pd
from sklearn.datasets import fetch_openml
 
 
# ---------------------------------------------------------------------------
# Definición de columnas por tipo
# ---------------------------------------------------------------------------
 
ORDINAL_ORDERINGS = {
    "Street": ["Grvl", "Pave"],
    "Alley": ["NA", "Grvl", "Pave"],
    "LotShape": ["IR3", "IR2", "IR1", "Reg"],
    "Utilities": ["ELO", "NoSeWa", "NoSewr", "AllPub"],
    "LandSlope": ["Sev", "Mod", "Gtl"],
    "ExterQual": ["Po", "Fa", "TA", "Gd", "Ex"],
    "ExterCond": ["Po", "Fa", "TA", "Gd", "Ex"],
    "BsmtQual": ["NA", "Po", "Fa", "TA", "Gd", "Ex"],
    "BsmtCond": ["NA", "Po", "Fa", "TA", "Gd", "Ex"],
    "BsmtExposure": ["NA", "No", "Mn", "Av", "Gd"],
    "HeatingQC": ["Po", "Fa", "TA", "Gd", "Ex"],
    "CentralAir": ["N", "Y"],
    "KitchenQual": ["Po", "Fa", "TA", "Gd", "Ex"],
    "Functional": ["Sal", "Sev", "Maj2", "Maj1", "Mod", "Min2", "Min1", "Typ"],
    "FireplaceQu": ["NA", "Po", "Fa", "TA", "Gd", "Ex"],
    "GarageFinish": ["NA", "Unf", "RFn", "Fin"],
    "GarageQual": ["NA", "Po", "Fa", "TA", "Gd", "Ex"],
    "GarageCond": ["NA", "Po", "Fa", "TA", "Gd", "Ex"],
    "PavedDrive": ["N", "P", "Y"],
    "PoolQC": ["NA", "Fa", "TA", "Gd", "Ex"],
    "Fence": ["NA", "MnWw", "GdWo", "MnPrv", "GdPrv"],
}
 
NUMERIC_COLUMNS = [
    "MoSold", "YrSold", "LotFrontage", "LotArea", "OverallQual", "OverallCond",
    "YearBuilt", "YearRemodAdd", "MasVnrArea", "BsmtFinSF1", "BsmtFinSF2",
    "BsmtUnfSF", "TotalBsmtSF", "1stFlrSF", "2ndFlrSF", "LowQualFinSF",
    "GrLivArea", "BsmtFullBath", "BsmtHalfBath", "FullBath", "HalfBath",
    "BedroomAbvGr", "KitchenAbvGr", "TotRmsAbvGrd", "Fireplaces", "GarageYrBlt",
    "GarageCars", "GarageArea", "WoodDeckSF", "OpenPorchSF", "EnclosedPorch",
    "3SsnPorch", "ScreenPorch", "PoolArea", "MiscVal",
]
 
# Nominales "simples": una columna -> un bloque de dummies
NOMINAL_SINGLE_COLUMNS = [
    "MSSubClass",  # numérica en apariencia (20, 60, 90...) pero es un código
                   # de categoría de vivienda, no una magnitud ordenable
    "MSZoning", "LandContour", "LotConfig", "Neighborhood",
    "BldgType", "HouseStyle", "RoofStyle", "RoofMatl", "MasVnrType",
    "Foundation", "Heating", "Electrical", "GarageType", "MiscFeature",
    "SaleType", "SaleCondition",
]
 
# Pares de columnas que comparten el mismo dominio de valores posibles y
# deben fusionarse en un único bloque de dummies (col_a, col_b, prefijo)
NOMINAL_PAIRED_COLUMNS = [
    ("Condition1", "Condition2", "Condition"),
    ("Exterior1st", "Exterior2nd", "Exterior"),
    ("BsmtFinType1", "BsmtFinType2", "BsmtFinType"),
]
 
 
# ---------------------------------------------------------------------------
# Funciones auxiliares
# ---------------------------------------------------------------------------
 
def _build_uniform_map(categories):
    n = len(categories)
    if n == 1:
        return {categories[0]: 1.0}
    return {cat: i / (n - 1) for i, cat in enumerate(categories)}
 
 
def _encode_ordinal(df, orderings):
    out = pd.DataFrame(index=df.index)
    for col, order in orderings.items():
        if col not in df.columns:
            continue
        mapping = _build_uniform_map(order)
        series = df[col]
        if "NA" in order:
            series = series.fillna("NA")
        encoded = series.map(mapping)
        # Cualquier NaN remanente (categoría inesperada, o NA sin estar en
        # el orden) se fuerza a 0, tal como se pidió explícitamente
        out[col] = encoded.fillna(0.0)
    return out
 
 
def _normalize_numeric(df, columns):
    out = pd.DataFrame(index=df.index)
    for col in columns:
        if col not in df.columns:
            continue
        serie = df[col].astype(float)
        # min/max se calculan ignorando NaN (comportamiento default de pandas)
        min_v, max_v = serie.min(), serie.max()
        if max_v == min_v:
            out[col] = 0.0  # columna constante: se evita división por cero
        else:
            out[col] = (serie - min_v) / (max_v - min_v)
        # Los NaN (valores faltantes, ej. LotFrontage, MasVnrArea,
        # GarageYrBlt) se completan con 0 luego de escalar
        out[col] = out[col].fillna(0.0)
    return out
 
 
def _one_hot_single(df, columns):
    present = [c for c in columns if c in df.columns]
    sub = df[present].copy()
    if "MSSubClass" in sub.columns:
        sub["MSSubClass"] = sub["MSSubClass"].astype(str)
    return pd.get_dummies(sub, columns=present, prefix=present)
 
 
def _one_hot_paired(df, col_a, col_b, prefix):
    """One-hot fusionado para pares tipo Condition1/Condition2: ambas
    columnas comparten el dominio de valores posibles y no interesa
    distinguir en cuál de las dos apareció cada valor."""
    da = pd.get_dummies(df[col_a]) if col_a in df.columns else pd.DataFrame(index=df.index)
    db = pd.get_dummies(df[col_b]) if col_b in df.columns else pd.DataFrame(index=df.index)
 
    combined = da.add(db, fill_value=0)
    combined = (combined > 0).astype(int)
    combined.columns = [f"{prefix}_{c}" for c in combined.columns]
    return combined
 
 
# ---------------------------------------------------------------------------
# Preprocesamiento completo
# ---------------------------------------------------------------------------
 
def preprocess_ames(df):
    """
    Preprocesa el Ames Housing Dataset (df = ds['data'], sin la columna
    target y sin usar 'Id').
 
    Devuelve un DataFrame con:
        - columnas ordinales -> valor uniforme en [0, 1]
        - columnas numéricas -> normalizadas min-max en [0, 1]
        - columnas nominales -> one-hot (get_dummies), con Condition1/2,
          Exterior1st/2nd y BsmtFinType1/2 fusionadas en un solo bloque
    """
    ordinal_part = _encode_ordinal(df, ORDINAL_ORDERINGS)
    numeric_part = _normalize_numeric(df, NUMERIC_COLUMNS)
    nominal_single_part = _one_hot_single(df, NOMINAL_SINGLE_COLUMNS)
 
    paired_parts = [
        _one_hot_paired(df, col_a, col_b, prefix)
        for col_a, col_b, prefix in NOMINAL_PAIRED_COLUMNS
    ]
 
    df_final = pd.concat(
        [ordinal_part, numeric_part, nominal_single_part, *paired_parts],
        axis=1,
    )
    return df_final
 
 
if __name__ == "__main__":
    ds = fetch_openml(name="house_prices", as_frame=True)
    X_raw = ds["data"]
 
    X_processed = preprocess_ames(X_raw)
 
    print("Shape original:", X_raw.shape)
    print("Shape procesado:", X_processed.shape)
    print(X_processed.head())

Shape original: (1460, 80)
Shape procesado: (1460, 217)
   Street  Alley  LotShape  Utilities  LandSlope  ExterQual  ExterCond  \
0     1.0    0.0  1.000000        1.0        1.0       0.75        0.5
1     1.0    0.0  1.000000        1.0        1.0       0.50        0.5
2     1.0    0.0  0.666667        1.0        1.0       0.75        0.5
3     1.0    0.0  0.666667        1.0        1.0       0.50        0.5
4     1.0    0.0  0.666667        1.0        1.0       0.75        0.5

   BsmtQual  BsmtCond  BsmtExposure  ...  Exterior_Stone  Exterior_Stucco  \
0       0.8       0.6          0.25  ...               0                0
1       0.8       0.6          1.00  ...               0                0
2       0.8       0.6          0.50  ...               0                0
3       0.6       0.8          0.25  ...               0                0
4       0.8       0.6          0.75  ...               0                0

   Exterior_VinylSd  Exterior_WdShing  BsmtFinType_ALQ  BsmtFinType_BLQ  \
0                 1                 0                0                0
1                 0                 0                1                0
2                 1                 0                0                0
3                 0                 0                1                0
4                 1                 0                0                0

   BsmtFinType_GLQ  BsmtFinType_LwQ  BsmtFinType_Rec  BsmtFinType_Unf
0                1                0                0                1
1                0                0                0                1
2                1                0                0                1
3                0                0                0                1
4                1                0                0                1

[5 rows x 217 columns]

In [6]:
categoricas = [
    "MSSubClass",
    "MSZoning",
    "LandContour",
    "LotConfig",
    "Neighborhood",
    "Condition1",
    "Condition2",
    "BldgType",
    "HouseStyle",
    "RoofStyle",
    "RoofMatl",
    "Exterior1st",
    "Exterior2nd",
    "MasVnrType",
    "Foundation",
    "Heating",
    "Electrical",
    "GarageType",
    "MiscFeature",
    "SaleType",
    "SaleCondition"
]

Para poder trabajar con el orden de los datos categóricos que tienen orden implícito, le pedimos a Claude armar un código que convierta esos órdenes a valores numéricos, normalizados para que todos estén entre 0 y 1. En los casos donde un valor posible es NaN, este se convierte en 0 ya que suele indicar que el inmueble no tiene una determinada característica.

In [7]:
orderings = {
    "Street":        ["Grvl", "Pave"],
    "Alley":         ["NA", "Grvl", "Pave"],
    "LotShape":      ["IR3", "IR2", "IR1", "Reg"],
    "Utilities":     ["ELO", "NoSeWa", "NoSewr", "AllPub"],
    "LandSlope":     ["Sev", "Mod", "Gtl"],
    "ExterQual":     ["Po", "Fa", "TA", "Gd", "Ex"],
    "ExterCond":     ["Po", "Fa", "TA", "Gd", "Ex"],
    "BsmtQual":      ["NA", "Po", "Fa", "TA", "Gd", "Ex"],
    "BsmtCond":      ["NA", "Po", "Fa", "TA", "Gd", "Ex"],
    "BsmtExposure":  ["NA", "No", "Mn", "Av", "Gd"],
    "BsmtFinType1":  ["NA", "Unf", "LwQ", "Rec", "BLQ", "ALQ", "GLQ"],
    "BsmtFinType2":  ["NA", "Unf", "LwQ", "Rec", "BLQ", "ALQ", "GLQ"],
    "HeatingQC":     ["Po", "Fa", "TA", "Gd", "Ex"],
    "CentralAir":    ["N", "Y"],
    "KitchenQual":   ["Po", "Fa", "TA", "Gd", "Ex"],
    "Functional":    ["Sal", "Sev", "Maj2", "Maj1", "Mod", "Min2", "Min1", "Typ"],
    "FireplaceQu":   ["NA", "Po", "Fa", "TA", "Gd", "Ex"],
    "GarageFinish":  ["NA", "Unf", "RFn", "Fin"],
    "GarageQual":    ["NA", "Po", "Fa", "TA", "Gd", "Ex"],
    "GarageCond":    ["NA", "Po", "Fa", "TA", "Gd", "Ex"],
    "PavedDrive":    ["N", "P", "Y"],
    "PoolQC":        ["NA", "Fa", "TA", "Gd", "Ex"],
    "Fence":         ["NA", "MnWw", "GdWo", "MnPrv", "GdPrv"],
}
 
 
# --- 3. Función auxiliar: lista ordenada -> diccionario de valores 0..1 ---
def build_uniform_map(categories):
    n = len(categories)
    if n == 1:
        return {categories[0]: 1.0}
    return {cat: i / (n - 1) for i, cat in enumerate(categories)}
 
 
# --- 4. Construir la nueva tabla ------------------------------------------
df_ord = X.copy()
 
for col, order in orderings.items():
    if col not in df_ord.columns:
        print(f"Aviso: la columna '{col}' no está en el dataset, se omite.")
        continue
 
    mapping = build_uniform_map(order)
    series = df_ord[col]
 
    # Si "NA" es una categoría válida en el orden, los NaN reales de pandas
    # representan esa categoría (ausencia de la característica).
    if "NA" in order:
        series = series.fillna("NA")
 
    df_ord[col] = series.map(mapping)
 
    # Chequeo de categorías inesperadas (no contempladas en el orden)
    n_missing = df_ord[col].isna().sum()
    if n_missing > 0:
        valores_raros = X.loc[df_ord[col].isna(), col].unique()
        print(
            f"Aviso: {col} tiene {n_missing} valores no mapeados. "
            f"Categorías no contempladas: {valores_raros}"
        )
 
# --- 5. Resultado -----------------------------------------------------------
if __name__ == "__main__":
    cols_transformadas = list(orderings.keys())
    print(df_ord[cols_transformadas].head())

   Street  Alley  LotShape  Utilities  LandSlope  ExterQual  ExterCond  \
0     1.0    0.0  1.000000        1.0        1.0       0.75        0.5
1     1.0    0.0  1.000000        1.0        1.0       0.50        0.5
2     1.0    0.0  0.666667        1.0        1.0       0.75        0.5
3     1.0    0.0  0.666667        1.0        1.0       0.50        0.5
4     1.0    0.0  0.666667        1.0        1.0       0.75        0.5

   BsmtQual  BsmtCond  BsmtExposure  ...  CentralAir  KitchenQual  Functional  \
0       0.8       0.6          0.25  ...         1.0         0.75         1.0
1       0.8       0.6          1.00  ...         1.0         0.50         1.0
2       0.8       0.6          0.50  ...         1.0         0.75         1.0
3       0.6       0.8          0.25  ...         1.0         0.75         1.0
4       0.8       0.6          0.75  ...         1.0         0.75         1.0

   FireplaceQu  GarageFinish  GarageQual  GarageCond  PavedDrive  PoolQC  \
0          0.0      0.666667         0.6         0.6         1.0     0.0
1          0.6      0.666667         0.6         0.6         1.0     0.0
2          0.6      0.666667         0.6         0.6         1.0     0.0
3          0.8      0.333333         0.6         0.6         1.0     0.0
4          0.6      0.666667         0.6         0.6         1.0     0.0

   Fence
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0

[5 rows x 23 columns]

In [8]:
np.min(df_ord['YrSold']) #2006
np.max(df_ord['YrSold']) #2010
df_ord_con_target = df_ord.copy()
df_ord_con_target['Target'] = y
df_ord_con_target[['YrSold','Target']].groupby(['YrSold']).mean()

               Target
YrSold
2006    182549.458599
2007    186063.151976
2008    177360.838816
2009    179432.103550
2010    177393.674286

Como el rango de años de venta considerado es muy bajo, no esperábamos un gran impacto de este atributo en el precio promedio, y esto se comprueba con la última consulta realizada.

Ahora procedemos a dividir los datos en desarrollo y evaluación. No se requiere ninguna forma particular de dividir los folds ya que cada instancia corresponde a una venta diferente. Tomaremos un 10% para test y dividiremos el resto en 5 folds.

In [52]:
X_train, X_test, target_train, target_test = train_test_split(df_ord, y, test_size=0.1, random_state=42,shuffle=True)

In [50]:
def regresion_hist_boosting(lista_max_depth,lista_min_samples_leaf,lista_max_features,train_data,train_target):
    pred_val_fold = []
    target_val_fold = []
    kfold = KFold(n_splits=5)
    for prof_max in lista_max_depth:
        for min_leaf in lista_min_samples_leaf:
            for max_feat in lista_max_features:
                model = HistGradientBoostingRegressor(loss='squared_error',max_depth=prof_max,min_samples_leaf=min_leaf,
                                              max_features=max_feat,random_state=42, categorical_features=categoricas)
                r2_prom = np.zeros(2)
                error_relativo_prom = 0
                for train_idx, val_idx in kfold.split(train_data,train_target):
                    X_train_fold, X_val_fold = train_data.iloc[train_idx], train_data.iloc[val_idx]
                    target_train_fold, target_val_fold = train_target.iloc[train_idx], train_target.iloc[val_idx]
                    model.fit(X_train_fold,target_train_fold)
                    pred_val_fold = model.predict(X_val_fold)
                    error_relativo_fold = np.mean(
                                            np.abs(pred_val_fold - target_val_fold) / target_val_fold
                                    )
                    error_relativo_prom += error_relativo_fold
                    r2_prom += np.array([r2_score(target_val_fold, pred_val_fold)])
                r2_prom = r2_prom/5
                error_relativo_prom /= 5
                print('etapa')
                print(prof_max,min_leaf,max_feat,'r2 promedio = ',r2_prom,error_relativo_prom)
    print(pred_val_fold)
    print(target_val_fold)

In [51]:
lista_max_depth = [3,5,7,None]
lista_min_samples_leaf = [1,5,25,50]
lista_max_features = [0.25,0.5,0.75,1.0]
regresion_hist_boosting(lista_max_depth,lista_min_samples_leaf,lista_max_features,X_train,target_train)

#la última combinación de hiperparámetros utilizada tiene un error absoluto medio aproximado de 27048.
#Es un buen inicio pero hay que mejorarlo.

etapa
3 1 0.25 r2 promedio =  [0.88919211 0.88919211] 0.09273992660247408
etapa
3 1 0.5 r2 promedio =  [0.88606261 0.88606261] 0.09324552846091702
etapa
3 1 0.75 r2 promedio =  [0.8924835 0.8924835] 0.09480341607882294
etapa
3 1 1.0 r2 promedio =  [0.88922175 0.88922175] 0.09454508899444951
etapa
3 5 0.25 r2 promedio =  [0.88923397 0.88923397] 0.093896837793565
etapa
3 5 0.5 r2 promedio =  [0.88792969 0.88792969] 0.0934575847762076
etapa
3 5 0.75 r2 promedio =  [0.89101285 0.89101285] 0.09443797781200787
etapa
3 5 1.0 r2 promedio =  [0.88842348 0.88842348] 0.09535181128961082
etapa
3 25 0.25 r2 promedio =  [0.88673331 0.88673331] 0.09288709443721208
etapa
3 25 0.5 r2 promedio =  [0.88757464 0.88757464] 0.09250217373717604
etapa
3 25 0.75 r2 promedio =  [0.88421601 0.88421601] 0.09386115512283197
etapa
3 25 1.0 r2 promedio =  [0.88410837 0.88410837] 0.09491047911729217
etapa
3 50 0.25 r2 promedio =  [0.87684824 0.87684824] 0.09464907143454984
etapa
3 50 0.5 r2 promedio =  [0.87714683 0.87714683] 0.09661730920938055
etapa
3 50 0.75 r2 promedio =  [0.87586112 0.87586112] 0.09740321234128982
etapa
3 50 1.0 r2 promedio =  [0.87526959 0.87526959] 0.09788328533935278
etapa
5 1 0.25 r2 promedio =  [0.8860335 0.8860335] 0.09204612178027342
etapa
5 1 0.5 r2 promedio =  [0.88888412 0.88888412] 0.09255651617227709
etapa
5 1 0.75 r2 promedio =  [0.88892296 0.88892296] 0.09331614447374792
etapa
5 1 1.0 r2 promedio =  [0.8760435 0.8760435] 0.0961877358621964
etapa
5 5 0.25 r2 promedio =  [0.89547729 0.89547729] 0.09007021493031804
etapa
5 5 0.5 r2 promedio =  [0.8914916 0.8914916] 0.09310145508946473
etapa
5 5 0.75 r2 promedio =  [0.88673361 0.88673361] 0.09245158974840653
etapa
5 5 1.0 r2 promedio =  [0.87939712 0.87939712] 0.09394502675909823
etapa
5 25 0.25 r2 promedio =  [0.89063658 0.89063658] 0.09126817990324457
etapa
5 25 0.5 r2 promedio =  [0.8902461 0.8902461] 0.09099002094730285
etapa
5 25 0.75 r2 promedio =  [0.88596091 0.88596091] 0.09306189763653072
etapa
5 25 1.0 r2 promedio =  [0.88857644 0.88857644] 0.09261632308872014
etapa
5 50 0.25 r2 promedio =  [0.88059061 0.88059061] 0.09325638901171489
etapa
5 50 0.5 r2 promedio =  [0.8803007 0.8803007] 0.0936374310951232
etapa
5 50 0.75 r2 promedio =  [0.88056673 0.88056673] 0.09322289631385779
etapa
5 50 1.0 r2 promedio =  [0.88067046 0.88067046] 0.09348726482645654
etapa
7 1 0.25 r2 promedio =  [0.88369593 0.88369593] 0.0930888221999074
etapa
7 1 0.5 r2 promedio =  [0.88256249 0.88256249] 0.09183505684261939
etapa
7 1 0.75 r2 promedio =  [0.8806515 0.8806515] 0.09367084888090665
etapa
7 1 1.0 r2 promedio =  [0.85893616 0.85893616] 0.09600652966519588
etapa
7 5 0.25 r2 promedio =  [0.89372736 0.89372736] 0.09132147272140388
etapa
7 5 0.5 r2 promedio =  [0.89057865 0.89057865] 0.09272266197169264
etapa
7 5 0.75 r2 promedio =  [0.88466044 0.88466044] 0.09237504220717273
etapa
7 5 1.0 r2 promedio =  [0.87673631 0.87673631] 0.09475675143371454
etapa
7 25 0.25 r2 promedio =  [0.89515864 0.89515864] 0.08790235208799549
etapa
7 25 0.5 r2 promedio =  [0.89052163 0.89052163] 0.09153560662748658
etapa
7 25 0.75 r2 promedio =  [0.88509841 0.88509841] 0.0934891280776181
etapa
7 25 1.0 r2 promedio =  [0.88606047 0.88606047] 0.09289577833316073
etapa
7 50 0.25 r2 promedio =  [0.87958598 0.87958598] 0.09302823311854788
etapa
7 50 0.5 r2 promedio =  [0.88377723 0.88377723] 0.09115360118139111
etapa
7 50 0.75 r2 promedio =  [0.88013068 0.88013068] 0.09331335847937726
etapa
7 50 1.0 r2 promedio =  [0.88123815 0.88123815] 0.09224073745723552
etapa
None 1 0.25 r2 promedio =  [0.8872163 0.8872163] 0.09108947611787696
etapa
None 1 0.5 r2 promedio =  [0.88832517 0.88832517] 0.09219979562198424
etapa
None 1 0.75 r2 promedio =  [0.88021434 0.88021434] 0.09227513992006883
etapa
None 1 1.0 r2 promedio =  [0.86137555 0.86137555] 0.09500592654386389
etapa
None 5 0.25 r2 promedio =  [0.89265646 0.89265646] 0.09091104389110258
etapa
None 5 0.5 r2 promedio =  [0.88961496 0.88961496] 0.09284206480634313
etapa
None 5 0.75 r2 promedio =  [0.88704441 0.88704441] 0.09232067021913345
etapa
None 5 1.0 r2 promedio =  [0.87983238 0.87983238] 0.0946055775396299
etapa
None 25 0.25 r2 promedio =  [0.89118374 0.89118374] 0.08964605014374101
etapa
None 25 0.5 r2 promedio =  [0.89099806 0.89099806] 0.09226161545189644
etapa
None 25 0.75 r2 promedio =  [0.88615004 0.88615004] 0.09362788881925925
etapa
None 25 1.0 r2 promedio =  [0.8876094 0.8876094] 0.09344766355274543
etapa
None 50 0.25 r2 promedio =  [0.88190521 0.88190521] 0.0930310655510628
etapa
None 50 0.5 r2 promedio =  [0.8820744 0.8820744] 0.09107692739301797
etapa
None 50 0.75 r2 promedio =  [0.88026145 0.88026145] 0.09301768493341273
etapa
None 50 1.0 r2 promedio =  [0.88145028 0.88145028] 0.0919444661839832
[109408.76003265  77926.85909057 219627.05876471 335000.59852634
 183551.45937139 191528.6185362  221254.64114313 141109.33918862
 100131.89947982 192374.09032616 186421.58036149 115573.99734576
  74573.47077905 114159.53134185 326964.68928304 349458.41564968
 279393.30626051 120773.46147359 141697.54447326 198339.32400437
  87417.98980178 144776.46908952 132344.13683366 133565.79925081
 219320.85240054 204082.69893642 160344.33680851  87644.65267297
  94659.85375222 143267.07231888 138368.73111206 177808.82785736
 147088.13367806 262728.50491562 158665.32282645 138984.25644091
 138186.12447965 307719.57572506 161310.48307434 243757.47402906
 134420.29110547 257032.00435025 149746.89242333  82469.41748163
 165333.6312384  102988.01261854 105817.14555915 128276.39009487
  94953.10071227 158777.98289694 186734.54399894 179926.11417361
 180845.95113035 193127.70726051 347970.20472359 229889.84830607
 159517.71621091 338065.44401097 288149.71613963 136753.45629747
 238280.90107329 218989.65182266 166925.33461638 237262.72327827
 145060.82419626 192131.68823685 105359.7667179  130687.44984619
 132593.31217819 302008.39027762 250094.07337074 110605.14268945
 249241.68874655 278714.60923224 146244.32436283 173444.83823896
 251015.96955493 177837.83516113 330524.1727664  139615.21694345
 143833.92008833 117954.4076364  142326.3727536  282093.29751292
 105911.11460303 119172.3036423  372371.90428691 144634.62154922
 188028.26600217  84085.08595292 150607.96954863 251874.62656875
 156563.80422827 103440.0969056  146046.98081315 118979.32421224
 162677.74495716 191112.47129182 138515.42808092 173513.76683546
 174740.23594528 261867.07606183 168766.2659524  140039.0233529
 177346.26705515 140919.0497109  116331.28094314 142896.75627309
 330290.85575201 127314.12779182 128902.04819767 287324.35152164
 196681.72054029 333024.98612135 145293.60493798 247006.34622004
 160716.50949147 138235.90805611 172382.85370124 138730.46004281
 158237.53904981 147813.44730092 178184.77802983 150125.08526777
 167715.53436154  93042.2918135  135477.52931021 112408.4952646
 189965.20419106  93164.09236303 148052.7888477  183300.36104048
 159760.09021156 233018.89616829 136094.8572498  354040.27293959
 238976.28048521 123679.68755576 117645.66918675 244188.2222748
  75651.80252604 117145.50862607 117261.34849839 129766.22867994
 162540.13544937 197005.63118372 226971.39558077 151744.96243118
 129986.49682957 150181.93683843 184477.18945337 139219.19517015
 229887.2554135  143955.48257854 379937.26441037 113444.78369183
  94266.21219305 215610.84476287 144661.14155003 127325.71642902
  84287.9062213  145591.87231189 216073.88832961  90203.00569169
 223578.78414685 145005.95217747 254640.08319276 157015.49754696
 174352.99400996 186035.87775009 117933.46351051 299852.47696286
 204355.23887213 157987.34910743 152625.71123317 148626.71113569
 221025.96490547 148661.81345043 152464.40679163 232818.61808604
 138067.88739071 170881.55873878 241072.43627666 194903.47846172
 145656.28657545 109319.18954746 168826.46153471 406638.53166907
  89861.05308027 180620.82766684 404182.55277766 129864.19453899
 113565.85853802 196824.76474417 116513.35615498 108019.57721891
 176701.9845004  276612.28208441 168803.44731384 143123.2265653
 138307.9676416  243319.92858058 123008.77732258 165069.83417554
 145271.96984935 257641.515278   220463.29648761 221033.3722608
  87855.05654761 210148.17957335 175397.79416485 238224.44294879
 129289.04096215 145680.33484024 217701.71922874 122692.73421125
 345322.45634488  98757.64921721 206129.47735796 153499.36637103
 360232.57972537 114682.59407362 139371.1417158  217557.79978842
 128598.24733084 307351.24534895 163117.88788222 202343.73473347
 161669.6377162  193360.15726244 272411.88800078 158407.68381196
 239582.51721737 174505.70217303 128515.37795124  59876.5891005
 111198.31623346 226290.25537747 205586.0714008  187370.31469943
 112757.92558489 179693.19740475 233350.46458951 385503.78129134
 276223.56695547 431680.34049722 109956.53856264 219555.64198126
 193438.27570194 110361.08636088 154355.78535429 166476.34578112
 140648.16072578 132162.34082259 183821.62975983  89597.66342364
 316662.8790818  173600.13427139 151758.40375095 118672.51956473
 162798.92472444 191824.07357205]
1186     95000
821      93000
1237    195000
877     350000
913     145000
         ...
1095    176432
1130    135000
1294    115000
860     189950
1126    174000
Name: SalePrice, Length: 262, dtype: int64

Dado que el precio de venta de un inmueble depende de sus características registradas, es de esperar que si dos inmuebles tienen valores muy similares en los features también tengan precios de venta parecidos. Por eso probaremos una estrategia de regresión con k-vecinos más cercanos. El desafío es definir la distancia entre dos inmuebles, ya que los distintos atributos no tienen necesariamente la misma importancia ni los mismos valores posibles. Para los atributos numéricos implementaremos una normalización para que tomen valores entre 0 y 1, lo mismo que ya hicimos con los atributos ordinales. En el caso de los categóricos, sumaremos 1 por cada atributo que tome un valor diferente en los dos inmuebles comparados. Esta forma de medir no toma en cuenta la importancia de los features, y puede representar algún grado de sobre o subdimensionamiento de cada feature. Para intentar reducir el impacto de este problema, usaremos k=10, que es un número pequeño porque representa menos del 1% de las instancias totales. Esperamos que de esa forma todos los 10 vecinos de un inmueble sean muy similares entre sí y eso nos dé un valor representativo. El valor de venta predicho de un inmueble será el promedio de los valores de venta de sus 10 vecinos más cercanos en el conjunto de entrenamiento.

In [54]:
X_train, X_test, target_train, target_test = train_test_split(X_processed, y, test_size=0.1, random_state=42,shuffle=True)

In [55]:
X_train_arr = X_train.to_numpy()
X_test_arr = X_test.to_numpy()
target_train_arr = target_train.to_numpy()
target_test_arr = target_test.to_numpy()
X_train_arr = X_train.astype(float).to_numpy()
X_test_arr = X_test.astype(float).to_numpy()

In [15]:
from sklearn.neighbors import KNeighborsRegressor
from scipy.spatial.distance import pdist, cdist, squareform

In [13]:
kfold = KFold(5)
pesos = 'uniform'

In [16]:
cols_object = X_train.select_dtypes(include='object').columns
print(cols_object)
print(X_train[cols_object].head())

Index([], dtype='object')
Empty DataFrame
Columns: []
Index: [907, 782, 952, 620, 669]

In [17]:
print(X_train.dtypes.value_counts())
print(X_train.dtypes.unique())

bool       127
float64     56
int32       34
Name: count, dtype: int64
[dtype('float64') dtype('bool') dtype('int32')]

In [18]:
for col in X_train.columns:
    try:
        X_train[col].astype(float)
    except Exception as e:
        print(col, "->", X_train[col].dtype, "->", e)

In [24]:
pesos = 'distance'
X_train_arr = X_train.to_numpy()
X_test_arr = X_test.to_numpy()
target_train_arr = target_train.to_numpy()
target_test_arr = target_test.to_numpy()
X_train_arr = X_train.astype(float).to_numpy()
X_test_arr = X_test.astype(float).to_numpy()

# Matriz de distancias L1 entre todos los pares del conjunto de entrenamiento

knn = KNeighborsRegressor(n_neighbors=10, metric='precomputed',weights=pesos)

r2_prom = 0 
mse = 0
for train_idx, val_idx in kfold.split(X_train_arr,target_train_arr):
    X_train_fold, X_val_fold = X_train_arr[train_idx], X_train_arr[val_idx]
    target_train_fold, target_val_fold = target_train_arr[train_idx], target_train_arr[val_idx]
    dist_train = squareform(pdist(X_train_fold, metric='cityblock'))
    knn.fit(dist_train,target_train_fold)
    dist_val_fold = cdist(X_val_fold, X_train_fold, metric='cityblock')
    pred_val_fold = knn.predict(dist_val_fold)
    mse += mean_squared_error(target_val_fold,pred_val_fold)
    r2_prom += r2_score(target_val_fold, pred_val_fold)
r2_prom = r2_prom/5
mse = mse/5
print(r2_prom)
print(mse)

0.7420274356883537
1561719698.7461686

In [23]:
k = 10
rng = np.random.default_rng(42)  # fija la semilla para reproducibilidad; sacala si querés que cambie en cada corrida
idx_random = rng.integers(0, X_train_arr.shape[0])

instancia_vec = X_train_arr[idx_random].reshape(1, -1)
precio_instancia = target_train_arr[idx_random]

# Distancia L1 de la instancia elegida a todo el resto del train
dist_a_train = cdist(instancia_vec, X_train_arr, metric='cityblock')[0]

# La instancia pertenece al propio X_train, así que su "vecino" más cercano
# sería ella misma con distancia 0 -> la excluimos
dist_a_train[idx_random] = np.inf

idx_vecinos = np.argsort(dist_a_train)[:k]
distancias_vecinos = dist_a_train[idx_vecinos]

print(f"Instancia elegida (posición {idx_random} en X_train):\n")
print(X_train.iloc[idx_random])
print(f"\nPrecio de venta real: {precio_instancia}\n")
print("=" * 60)

for rank, (i, dist) in enumerate(zip(idx_vecinos, distancias_vecinos), start=1):
    print(f"\nVecino #{rank} (posición {i}, distancia L1 = {dist:.4f}):\n")
    print(X_train.iloc[i])
    print(f"\nPrecio de venta: {target_train_arr[i]}")
    print("-" * 60)

promedio_vecinos = target_train_arr[idx_vecinos].mean()
print(f"\nPromedio de precios de los {k} vecinos (predicción KNN): {promedio_vecinos:.2f}")

Instancia elegida (posición 117 en X_train):

Street             1.0
Alley              0.0
LotShape           1.0
Utilities          1.0
LandSlope          0.5
                  ...
BsmtFinType_BLQ      0
BsmtFinType_GLQ      1
BsmtFinType_LwQ      0
BsmtFinType_Rec      0
BsmtFinType_Unf      1
Name: 426, Length: 217, dtype: object

Precio de venta real: 275000

============================================================

Vecino #1 (posición 92, distancia L1 = 12.7231):

Street                  1.0
Alley                   0.0
LotShape           0.666667
Utilities               1.0
LandSlope               0.5
                     ...
BsmtFinType_BLQ           0
BsmtFinType_GLQ           1
BsmtFinType_LwQ           0
BsmtFinType_Rec           0
BsmtFinType_Unf           1
Name: 208, Length: 217, dtype: object

Precio de venta: 277000
------------------------------------------------------------

Vecino #2 (posición 440, distancia L1 = 13.1730):

Street             1.0
Alley              0.0
LotShape           1.0
Utilities          1.0
LandSlope          1.0
                  ...
BsmtFinType_BLQ      0
BsmtFinType_GLQ      1
BsmtFinType_LwQ      0
BsmtFinType_Rec      0
BsmtFinType_Unf      1
Name: 319, Length: 217, dtype: object

Precio de venta: 187500
------------------------------------------------------------

Vecino #3 (posición 1153, distancia L1 = 13.1956):

Street             1.0
Alley              0.0
LotShape           0.0
Utilities          1.0
LandSlope          1.0
                  ...
BsmtFinType_BLQ      0
BsmtFinType_GLQ      1
BsmtFinType_LwQ      0
BsmtFinType_Rec      0
BsmtFinType_Unf      1
Name: 1348, Length: 217, dtype: object

Precio de venta: 215000
------------------------------------------------------------

Vecino #4 (posición 1013, distancia L1 = 13.1992):

Street                  1.0
Alley                   0.0
LotShape           0.666667
Utilities               1.0
LandSlope               1.0
                     ...
BsmtFinType_BLQ           0
BsmtFinType_GLQ           1
BsmtFinType_LwQ           0
BsmtFinType_Rec           0
BsmtFinType_Unf           1
Name: 1258, Length: 217, dtype: object

Precio de venta: 190000
------------------------------------------------------------

Vecino #5 (posición 698, distancia L1 = 13.3647):

Street                  1.0
Alley                   0.0
LotShape           0.666667
Utilities               1.0
LandSlope               1.0
                     ...
BsmtFinType_BLQ           0
BsmtFinType_GLQ           0
BsmtFinType_LwQ           0
BsmtFinType_Rec           0
BsmtFinType_Unf           1
Name: 1124, Length: 217, dtype: object

Precio de venta: 163900
------------------------------------------------------------

Vecino #6 (posición 663, distancia L1 = 13.3824):

Street             1.0
Alley              0.0
LotShape           1.0
Utilities          1.0
LandSlope          1.0
                  ...
BsmtFinType_BLQ      0
BsmtFinType_GLQ      1
BsmtFinType_LwQ      0
BsmtFinType_Rec      0
BsmtFinType_Unf      1
Name: 667, Length: 217, dtype: object

Precio de venta: 193500
------------------------------------------------------------

Vecino #7 (posición 651, distancia L1 = 13.5854):

Street                  1.0
Alley                   0.0
LotShape           0.666667
Utilities               1.0
LandSlope               1.0
                     ...
BsmtFinType_BLQ           0
BsmtFinType_GLQ           1
BsmtFinType_LwQ           0
BsmtFinType_Rec           0
BsmtFinType_Unf           1
Name: 731, Length: 217, dtype: object

Precio de venta: 187500
------------------------------------------------------------

Vecino #8 (posición 1018, distancia L1 = 13.9063):

Street             1.0
Alley              0.0
LotShape           1.0
Utilities          1.0
LandSlope          0.5
                  ...
BsmtFinType_BLQ      0
BsmtFinType_GLQ      1
BsmtFinType_LwQ      0
BsmtFinType_Rec      0
BsmtFinType_Unf      1
Name: 476, Length: 217, dtype: object

Precio de venta: 208900
------------------------------------------------------------

Vecino #9 (posición 388, distancia L1 = 13.9362):

Street             1.0
Alley              0.0
LotShape           1.0
Utilities          1.0
LandSlope          0.5
                  ...
BsmtFinType_BLQ      0
BsmtFinType_GLQ      1
BsmtFinType_LwQ      0
BsmtFinType_Rec      0
BsmtFinType_Unf      1
Name: 318, Length: 217, dtype: object

Precio de venta: 260000
------------------------------------------------------------

Vecino #10 (posición 727, distancia L1 = 14.3145):

Street             1.0
Alley              0.0
LotShape           1.0
Utilities          1.0
LandSlope          1.0
                  ...
BsmtFinType_BLQ      0
BsmtFinType_GLQ      1
BsmtFinType_LwQ      0
BsmtFinType_Rec      0
BsmtFinType_Unf      1
Name: 530, Length: 217, dtype: object

Precio de venta: 175000
------------------------------------------------------------

Promedio de precios de los 10 vecinos (predicción KNN): 205830.00

Como predecir un precio con los k-vecinos más cercanos no funciona, el problema puede ser algo que ya sospechábamos: como los atributos son one hot o normalizados entre 0 y 1, puede estar ponderando de manera uniforme atributos con niveles de importancia muy distintos. Por eso, vamos a probar pesarlos con muchos vectores de pesos aleatorios, esperando que tal vez alguna combinación de pesos represente mejor la realidad del problema.

In [46]:
knn = KNeighborsRegressor(n_neighbors=10, metric='precomputed', weights='uniform')

resultados = []  # (índice del vector de pesos, R2 promedio, MSE promedio)

n_features = X_train_arr.shape[1]
n_vectores = 50

rng = np.random.default_rng(42)  # fija la semilla para reproducibilidad; sacala si querés que cambien en cada corrida
pesos_candidatos = rng.uniform(low=0.0, high=10.0, size=(n_vectores, n_features))

print(pesos_candidatos.shape)  # (100, n_features)

for idx_peso, w in enumerate(pesos_candidatos):
    #X_train_w = X_train_arr * w  # escalado elemento a elemento (implementa la L1 ponderada)
    X_train_w = X_train_arr * np.sqrt(w)
    r2_prom = 0
    mse_prom = 0
    error_relativo_prom = 0

    for train_idx, val_idx in kfold.split(X_train_w, target_train_arr):
        X_train_fold, X_val_fold = X_train_w[train_idx], X_train_w[val_idx]
        target_train_fold, target_val_fold = target_train_arr[train_idx], target_train_arr[val_idx]

        dist_train_fold = squareform(pdist(X_train_fold, metric='euclidean')) #poner cityblock para que sea norma 1.
        knn.fit(dist_train_fold, target_train_fold)

        dist_val_fold = cdist(X_val_fold, X_train_fold, metric='euclidean')
        pred_val_fold = knn.predict(dist_val_fold)

        mse_prom += mean_squared_error(target_val_fold, pred_val_fold)
        r2_prom += r2_score(target_val_fold, pred_val_fold)
        error_relativo_fold = np.mean(
                        np.abs(pred_val_fold - target_val_fold) / target_val_fold
                )
        error_relativo_prom += error_relativo_fold

    r2_prom /= 5
    mse_prom /= 5
    error_relativo_prom /= 5

    resultados.append((idx_peso, r2_prom, mse_prom))
    print(f"Pesos #{idx_peso}: R2 promedio = {r2_prom:.4f} | error relativo promedio = {error_relativo_prom:.2f}")

# Mejor vector de pesos según R2
mejor = max(resultados, key=lambda x: x[1])
print(f"\nMejor vector de pesos: #{mejor[0]} con R2 = {mejor[1]:.4f} y MSE = {mejor[2]:.2f}") #el mejor da R^2 = 0.74 para uniform, 0.75 para distance
#los resultados empeoran con la norma 2 respecto de la norma 1, con un máximo de 0.71.

(50, 217)
Pesos #0: R2 promedio = 0.6650 | error relativo promedio = 0.15
Pesos #1: R2 promedio = 0.6841 | error relativo promedio = 0.16
Pesos #2: R2 promedio = 0.6506 | error relativo promedio = 0.16
Pesos #3: R2 promedio = 0.6795 | error relativo promedio = 0.16
Pesos #4: R2 promedio = 0.6757 | error relativo promedio = 0.16
Pesos #5: R2 promedio = 0.6714 | error relativo promedio = 0.16
Pesos #6: R2 promedio = 0.6712 | error relativo promedio = 0.16
Pesos #7: R2 promedio = 0.6762 | error relativo promedio = 0.16
Pesos #8: R2 promedio = 0.6649 | error relativo promedio = 0.16
Pesos #9: R2 promedio = 0.7028 | error relativo promedio = 0.15
Pesos #10: R2 promedio = 0.6654 | error relativo promedio = 0.16
Pesos #11: R2 promedio = 0.6689 | error relativo promedio = 0.16
Pesos #12: R2 promedio = 0.7050 | error relativo promedio = 0.15
Pesos #13: R2 promedio = 0.6742 | error relativo promedio = 0.16
Pesos #14: R2 promedio = 0.7005 | error relativo promedio = 0.15
Pesos #15: R2 promedio = 0.6695 | error relativo promedio = 0.16
Pesos #16: R2 promedio = 0.6940 | error relativo promedio = 0.15
Pesos #17: R2 promedio = 0.6943 | error relativo promedio = 0.15
Pesos #18: R2 promedio = 0.6712 | error relativo promedio = 0.16
Pesos #19: R2 promedio = 0.6776 | error relativo promedio = 0.16
Pesos #20: R2 promedio = 0.6667 | error relativo promedio = 0.16
Pesos #21: R2 promedio = 0.6929 | error relativo promedio = 0.15
Pesos #22: R2 promedio = 0.6832 | error relativo promedio = 0.16
Pesos #23: R2 promedio = 0.6799 | error relativo promedio = 0.15
Pesos #24: R2 promedio = 0.6524 | error relativo promedio = 0.16
Pesos #25: R2 promedio = 0.6792 | error relativo promedio = 0.16
Pesos #26: R2 promedio = 0.6944 | error relativo promedio = 0.15
Pesos #27: R2 promedio = 0.6485 | error relativo promedio = 0.16
Pesos #28: R2 promedio = 0.6547 | error relativo promedio = 0.17
Pesos #29: R2 promedio = 0.6791 | error relativo promedio = 0.16
Pesos #30: R2 promedio = 0.6488 | error relativo promedio = 0.16
Pesos #31: R2 promedio = 0.6799 | error relativo promedio = 0.16
Pesos #32: R2 promedio = 0.6802 | error relativo promedio = 0.16
Pesos #33: R2 promedio = 0.6775 | error relativo promedio = 0.16
Pesos #34: R2 promedio = 0.6898 | error relativo promedio = 0.16
Pesos #35: R2 promedio = 0.6946 | error relativo promedio = 0.16
Pesos #36: R2 promedio = 0.6863 | error relativo promedio = 0.16
Pesos #37: R2 promedio = 0.6811 | error relativo promedio = 0.16
Pesos #38: R2 promedio = 0.6840 | error relativo promedio = 0.16
Pesos #39: R2 promedio = 0.6863 | error relativo promedio = 0.16
Pesos #40: R2 promedio = 0.6705 | error relativo promedio = 0.16
Pesos #41: R2 promedio = 0.6786 | error relativo promedio = 0.16
Pesos #42: R2 promedio = 0.6566 | error relativo promedio = 0.17
Pesos #43: R2 promedio = 0.6735 | error relativo promedio = 0.16
Pesos #44: R2 promedio = 0.6532 | error relativo promedio = 0.16
Pesos #45: R2 promedio = 0.6614 | error relativo promedio = 0.16
Pesos #46: R2 promedio = 0.6842 | error relativo promedio = 0.16
Pesos #47: R2 promedio = 0.6543 | error relativo promedio = 0.16
Pesos #48: R2 promedio = 0.6665 | error relativo promedio = 0.16
Pesos #49: R2 promedio = 0.6853 | error relativo promedio = 0.15

Mejor vector de pesos: #12 con R2 = 0.7050 y MSE = 1795964903.13

Como el enfoque de k-vecinos más cercanos no funcionó, ni siquiera variando los pesos, probamos ahora con una regresión lineal. Ya que lo vamos a hacer sobre la base de datos preprocesada y muchos atributos son one hot de una misma categoría, las variables que vamos a usar están muy correlacionadas. Además de eso creemos que, de los atributos originales, los realmente importantes no son muchos. Por estos motivos, usaremos regularización Lasso, que tiende a dar soluciones con muchos parámetros muy pequeños o nulos.

In [ ]:
from sklearn.linear_model import Lasso

alphas = [0.1, 1, 10, 25, 50, 75, 100,250,500]
resultados_lasso = []  # (alpha, R2 promedio, MSE promedio)

for alpha in alphas:
    lasso = Lasso(alpha=alpha, random_state=42)

    r2_prom = 0
    mse_prom = 0

    for train_idx, val_idx in kfold.split(X_train_arr, target_train_arr):
        X_train_fold, X_val_fold = X_train_arr[train_idx], X_train_arr[val_idx]
        target_train_fold, target_val_fold = target_train_arr[train_idx], target_train_arr[val_idx]

        lasso.fit(X_train_fold, target_train_fold)
        pred_val_fold = lasso.predict(X_val_fold)

        mse_prom += mean_squared_error(target_val_fold, pred_val_fold)
        r2_prom += r2_score(target_val_fold, pred_val_fold)

    r2_prom /= 5
    mse_prom /= 5

    resultados_lasso.append((alpha, r2_prom, mse_prom))
    print(f"alpha = {alpha}: R2 promedio = {r2_prom:.4f} | MSE promedio = {mse_prom:.2f}")

mejor_alpha = max(resultados_lasso, key=lambda x: x[1])
print(f"\nMejor alpha: {mejor_alpha[0]} con R2 = {mejor_alpha[1]:.4f} y MSE = {mejor_alpha[2]:.2f}")

c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.019e+11, tolerance: 6.409e+08
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.928e+10, tolerance: 6.012e+08
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.007e+10, tolerance: 6.093e+08
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.167e+10, tolerance: 6.474e+08
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.411e+10, tolerance: 6.497e+08
  model = cd_fast.enet_coordinate_descent(

alpha = 0.1: R2 promedio = 0.8082 | MSE promedio = 1195055226.66

c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.696e+10, tolerance: 6.409e+08
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.838e+10, tolerance: 6.012e+08
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.077e+10, tolerance: 6.093e+08
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.716e+10, tolerance: 6.474e+08
  model = cd_fast.enet_coordinate_descent(
c:\Users\Lenny\Python39\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.216e+10, tolerance: 6.497e+08
  model = cd_fast.enet_coordinate_descent(

alpha = 1: R2 promedio = 0.8082 | MSE promedio = 1196680001.11
alpha = 10: R2 promedio = 0.8206 | MSE promedio = 1121453143.39
alpha = 25: R2 promedio = 0.8309 | MSE promedio = 1060347608.65
alpha = 50: R2 promedio = 0.8368 | MSE promedio = 1023254623.93
alpha = 75: R2 promedio = 0.8397 | MSE promedio = 1005268926.89
alpha = 100: R2 promedio = 0.8410 | MSE promedio = 996541637.80
alpha = 250: R2 promedio = 0.8383 | MSE promedio = 1004075333.11
alpha = 500: R2 promedio = 0.8240 | MSE promedio = 1083334832.70

Mejor alpha: 100 con R2 = 0.8410 y MSE = 996541637.80

Aunque los resultados superan visiblemente a los k-vecinos más cercanos, lo que puede ser señal de que estamos en el camino correcto, vemos que en general no convergió, lo que se demuestra con valores de tolerance altos y duality gaps mucho mayores. Esto posiblemente se deba a la enorme diferencia de escala entre las variables normalizadas y el target (precios de venta de inmuebles en dólares contra valores entre 0 y 1). Por eso, vamos a intentar de nuevo escalando también el target.

In [43]:
from sklearn.preprocessing import MinMaxScaler

target_scaler = MinMaxScaler()
target_train_scaled = target_scaler.fit_transform(target_train_arr.reshape(-1, 1)).flatten()

alphas = [0.0001, 0.001, 0.01, 0.1]
resultados_lasso = []  # (alpha, R2 promedio, MSE promedio en dólares²)

for alpha in alphas:
    lasso = Lasso(alpha=alpha, random_state=42, max_iter=100000)

    r2_prom = 0
    mse_prom_dolares = 0
    error_relativo_prom = 0

    for train_idx, val_idx in kfold.split(X_train_arr, target_train_scaled):
        X_train_fold, X_val_fold = X_train_arr[train_idx], X_train_arr[val_idx]
        target_train_fold_scaled = target_train_scaled[train_idx]
        target_val_fold_scaled = target_train_scaled[val_idx]

        lasso.fit(X_train_fold, target_train_fold_scaled)
        pred_val_fold_scaled = lasso.predict(X_val_fold)

        # Des-escalar predicción y target real para reportar en dólares
        pred_val_fold_dolares = target_scaler.inverse_transform(
            pred_val_fold_scaled.reshape(-1, 1)
        ).flatten()
        target_val_fold_dolares = target_scaler.inverse_transform(
            target_val_fold_scaled.reshape(-1, 1)
        ).flatten()
        error_relativo_fold = np.mean(
                np.abs(pred_val_fold_dolares - target_val_fold_dolares) / target_val_fold_dolares
        )

        mse_prom_dolares += mean_squared_error(target_val_fold_dolares, pred_val_fold_dolares)
        r2_prom += r2_score(target_val_fold_dolares, pred_val_fold_dolares)
        error_relativo_prom += error_relativo_fold

    r2_prom /= 5
    mse_prom_dolares /= 5
    error_relativo_prom /= 5
    resultados_lasso.append((alpha, r2_prom, mse_prom_dolares, error_relativo_prom))
    print(f"alpha = {alpha}: R2 promedio = {r2_prom:.4f} | Error relativo promedio = {error_relativo_prom:.2f}")

mejor_alpha = max(resultados_lasso, key=lambda x: x[1])
print(f"\nMejor alpha: {mejor_alpha[0]} con R2 = {mejor_alpha[1]:.4f} y MSE = {mejor_alpha[2]:.2f}")

alpha = 0.0001: R2 promedio = 0.8393 | Error relativo promedio = 0.11
alpha = 0.001: R2 promedio = 0.8091 | Error relativo promedio = 0.12
alpha = 0.01: R2 promedio = 0.4030 | Error relativo promedio = 0.25
alpha = 0.1: R2 promedio = -0.0054 | Error relativo promedio = 0.36

Mejor alpha: 0.0001 con R2 = 0.8393 y MSE = 1007722655.80

Para los primeros coeficientes de alpha probados: [0.1, 1, 10, 100], esto da un R^2 de -0.0054, muy cercano a 0. Esto es el resultado cuando se predice siempre el promedio de todas las instancias. El motivo, que se confirma con el siguiente bloque de código, es que todos los coeficientes fueron llevados a 0 porque los alpha utilizados (iguales a los de antes) conllevaron una regularización excesiva (valores alpha entre 0.1 y 100). Buscaremos arreglarlo reduciendo la escala.

Con valores alpha = 0.0001, 0.001, 0.01, 0.1, se tiene valores R^2 promedio de 0.84, 0.81, 0.4030, -0.0054 respectivamente. Se ve que el menor alpha de todos no funciona mal, pero ver el deterioro de los resultados con el crecimiento de este parámetro nos invita a buscar el mejor en un rango aún más chico: 0.0000001, 0.000001, 0.00001, 0.0001. Todos en este rango superan el R^2 de 0.80, pero el mejor sigue siendo 0.0001, por lo que buscaremos más profundamente en este orden de magnitud. 

Como resultado, el mejor R^2 (0.84) se obtiene con alpha = 0.0002, pero no aporta una diferencia significativa con respecto a 0.0001 o 0.0003. En todos los k*10^{-4}, con k entre 0 y 9, el error relativo promedio da 0.11 o 0.12. Para comparar esta nueva métrica, corremos de nuevo los alpha anteriores que nos daban peor. Para los originales, entre 0.1 y 100, los errores relativos promedio dan 0.36.

In [36]:
print((lasso.coef_ != 0).sum(), "de", len(lasso.coef_), "coeficientes distintos de cero")
print(lasso.intercept_)

36 de 217 coeficientes distintos de cero
-0.09057142779948252

Vemos que el mejor método de regresión utilizado en este trabajo es el HistBoostingRegressor, seguido muy de cerca por la regresión lineal con regularización Lasso con alpha del orden de magnitud adecuado. Finalmente evaluamos ambos con todo el conjunto de entrenamiento para ver los resultados en el conjunto de test.

In [53]:
pred_val_fold = []
target_val_fold = []
kfold = KFold(n_splits=5)
for prof_max in lista_max_depth:
    for min_leaf in lista_min_samples_leaf:
        for max_feat in lista_max_features:
            model = HistGradientBoostingRegressor(loss='squared_error',max_depth=prof_max,min_samples_leaf=min_leaf,
                                              max_features=max_feat,random_state=42, categorical_features=categoricas)
            model.fit(X_train,target_train)
            pred_val = model.predict(X_test)
            error_relativo = np.mean(np.abs(pred_val - target_test) / target_test)
            r2= r2_score(target_test, pred_val)
            print('etapa')
            print(prof_max,min_leaf,max_feat,'r2 promedio = ',r2_prom,error_relativo_prom)

etapa
3 1 0.25 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
3 1 0.5 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
3 1 0.75 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
3 1 1.0 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
3 5 0.25 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
3 5 0.5 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
3 5 0.75 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
3 5 1.0 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
3 25 0.25 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
3 25 0.5 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
3 25 0.75 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
3 25 1.0 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
3 50 0.25 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
3 50 0.5 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
3 50 0.75 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
3 50 1.0 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
5 1 0.25 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
5 1 0.5 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
5 1 0.75 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
5 1 1.0 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
5 5 0.25 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
5 5 0.5 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
5 5 0.75 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
5 5 1.0 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
5 25 0.25 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
5 25 0.5 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
5 25 0.75 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
5 25 1.0 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
5 50 0.25 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
5 50 0.5 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
5 50 0.75 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
5 50 1.0 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
7 1 0.25 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
7 1 0.5 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
7 1 0.75 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
7 1 1.0 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
7 5 0.25 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
7 5 0.5 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
7 5 0.75 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
7 5 1.0 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
7 25 0.25 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
7 25 0.5 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
7 25 0.75 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
7 25 1.0 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
7 50 0.25 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
7 50 0.5 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
7 50 0.75 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
7 50 1.0 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
None 1 0.25 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
None 1 0.5 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
None 1 0.75 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
None 1 1.0 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
None 5 0.25 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
None 5 0.5 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
None 5 0.75 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
None 5 1.0 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
None 25 0.25 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
None 25 0.5 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
None 25 0.75 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
None 25 1.0 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
None 50 0.25 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
None 50 0.5 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
None 50 0.75 r2 promedio =  0.6853008030134451 0.15366540833097503
etapa
None 50 1.0 r2 promedio =  0.6853008030134451 0.15366540833097503

Notamos que el HistBoostingRegressor sobreajustó, ya que se observa de forma consistente un mayor error relativo que durante la etapa de desarrollo. Creemos que no va a ocurrir con la regresión Lasso, ya que convierte muchos parámetros en 0 para prevenir sobreajustes.

In [56]:
alpha = 0.0002

lasso_final = Lasso(alpha=alpha, random_state=42, max_iter=100000)
lasso_final.fit(X_train_arr, target_train_scaled)

# Predicción sobre test, en la escala [0,1] del target
pred_test_scaled = lasso_final.predict(X_test_arr)

# Des-escalar con el mismo target_scaler ajustado sobre target_train_arr
# (NO se vuelve a fitear con datos de test, para no filtrar información)
pred_test_dolares = target_scaler.inverse_transform(
    pred_test_scaled.reshape(-1, 1)
).flatten()
target_test_dolares = target_test_arr  # ya está en dólares, sin escalar

mse_test = mean_squared_error(target_test_dolares, pred_test_dolares)
r2_test = r2_score(target_test_dolares, pred_test_dolares)
error_relativo_test = np.mean(
    np.abs(pred_test_dolares - target_test_dolares) / target_test_dolares
)

print(f"R2 en test = {r2_test:.4f}")
print(f"MSE en test (dólares^2) = {mse_test:.2f}")
print(f"Error relativo promedio en test = {error_relativo_test:.4f} ({error_relativo_test*100:.2f}%)")

R2 en test = 0.8535
MSE en test (dólares^2) = 1338486787.17
Error relativo promedio en test = 0.1083 (10.83%)

El error relativo promedio se mantiene en 0.11 aproximadamente, es decir que mantiene el buen resultado de la etapa de desarrollo. Por lo tanto, elegimos la regularización Lasso con parámetro alpha = 0.0002 como modelo final.